### ISSUE TITLE
[DOCS] instructions are not clear; Fail to install 

### ISSUE THREAD

**Issue by auniyal61** [ether/ep_table_of_contents#154]
Installation
`npm i ep_table_of_contents`  ref: https://www.npmjs.com/package/ep_table_of_contents

this created package.json

restart etherpad_lite service; 
Service could not restart and failed with error log, This should not have happend, as a User I should be able to opt-in or opt-out to use plugin.

```
Sep 13 19:29:43 fedora etherpad[303289]: [2024-09-13 19:29:43.494] [INFO] plugins - Running npm to get a list of installed plugins...                                                         
Sep 13 19:29:45 fedora etherpad[303289]: [2024-09-13 19:29:45.113] [ERROR] runCmd|npm - npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.js
on was generated for lockfileVersion@2. I'll try to do my best with it!                                                                                                                       
Sep 13 19:29:45 fedora etherpad[303289]: [2024-09-13 19:29:45.126] [ERROR] runCmd|npm - npm ERR! missing: ep_table_of_contents@0.3.86, required by etherpad-lite                              
Sep 13 19:29:45 fedora etherpad[303289]: [2024-09-13 19:29:45.138] [ERROR] server - Error occurred while starting Etherpad                                                                    
Sep 13 19:29:45 fedora etherpad[303289]: [2024-09-13 19:29:45.139] [ERROR] server - Metrics at time of fatal error:       
```

Config:
I did not had settings.json by default in my repo root dir. So I copied settings.json.template as settings.json 

added suggested key: value at the end

```
"ep_toc": {
  "disable_by_default": false,
  "show_button": true
},
```

Failed with Logs

**Removed the plugin, to restore service**
`npm uninstall ep_table_of_contents`

this updated package.json as expected

Removed added key:value from settings.json

restarted service logs:

```
Sep 13 19:35:55 fedora etherpad[304058]: [2024-09-13 19:35:55.993] [WARN] console - Update available: Download the actual version 2.1.1
Sep 13 19:36:14 fedora etherpad[304058]: [2024-09-13 19:36:14.584] [INFO] plugins - Running npm to get a list of installed plugins...
Sep 13 19:36:16 fedora etherpad[304058]: [2024-09-13 19:36:16.184] [ERROR] runCmd|npm - npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
Sep 13 19:36:17 fedora etherpad[304058]: [2024-09-13 19:36:17.186] [ERROR] runCmd|npm - npm ERR! extraneous: ep_etherpad-lite@1.9.2 /home/auniyal/custom_services/etherpad-lite/node_modules/ep_etherpad-lite
Sep 13 19:36:17 fedora etherpad[304058]: [2024-09-13 19:36:17.198] [ERROR] server - Error occurred while starting Etherpad
Sep 13 19:36:17 fedora etherpad[304058]: [2024-09-13 19:36:17.199] [ERROR] server - Metrics at time of fatal error:
Sep 13 19:36:17 fedora etherpad[304058]: {
Sep 13 19:36:17 fedora etherpad[304058]:   "httpStartTime": 0,
Sep 13 19:36:17 fedora etherpad[304058]:   "memoryUsage": 239534080,
Sep 13 19:36:17 fedora etherpad[304058]:   "memoryUsageHeap": 162607464,
Sep 13 19:36:17 fedora etherpad[304058]:   "ueberdb_lockAwaits": 0,
Sep 13 19:36:17 fedora etherpad[304058]:   "ueberdb_lockAcquires": 0,
Sep 13 19:36:17 fedora etherpad[304058]:   "ueberdb_lockReleases": 0,
Sep 13 19:36:17 fedora etherpad[304058]:   "ueberdb_reads": 0,
Sep 13 19:36:17 fedora etherpad[304058]:   "ueberdb_readsFailed": 0,
Sep 13 19:36:17 fedora etherpad[304058]:   "ueberdb_readsFinished": 0,
Sep 13 19:36:17 fedora etherpad[304058]:   "ueberdb_readsFromCache": 0,
Sep 13 19:36:17 fedora etherpad[304058]:   "ueberdb_readsFromDb": 0,
Sep 13 19:36:17 fedora etherpad[304058]:   "ueberdb_readsFromDbFailed": 0,
Sep 13 19:36:17 fedora etherpad[304058]:   "ueberdb_readsFromDbFinished": 0,
Sep 13 19:36:17 fedora etherpad[304058]:   "ueberdb_writes": 0,
Sep 13 19:36:17 fedora etherpad[304058]:   "ueberdb_writesFailed": 0,
Sep 13 19:36:17 fedora etherpad[304058]:   "ueberdb_writesFinished": 0,
Sep 13 19:36:17 fedora etherpad[304058]:   "ueberdb_writesObsoleted": 0,
Sep 13 19:36:17 fedora etherpad[304058]:   "ueberdb_writesToDb": 0,
Sep 13 19:36:17 fedora etherpad[304058]:   "ueberdb_writesToDbFailed": 0,
Sep 13 19:36:17 fedora etherpad[304058]:   "ueberdb_writesToDbFinished": 0,
Sep 13 19:36:17 fedora etherpad[304058]:   "ueberdb_writesToDbRetried": 0
Sep 13 19:36:17 fedora etherpad[304058]: }
Sep 13 19:36:17 fedora etherpad[304058]: [2024-09-13 19:36:17.199] [ERROR] server - Error: Command exited with code 1: npm ls --long --json --depth=0 --no-production
Sep 13 19:36:17 fedora etherpad[304058]:     at exports (/home/auniyal/custom_services/etherpad-lite/src/node/utils/run_cmd.js:119:25)
Sep 13 19:36:17 fedora etherpad[304058]:     at Object.exports.getPackages (/home/auniyal/custom_services/etherpad-lite/src/static/js/pluginfw/plugins.js:115:48)
Sep 13 19:36:17 fedora etherpad[304058]:     at Object.exports.update (/home/auniyal/custom_services/etherpad-lite/src/static/js/pluginfw/plugins.js:86:34)
Sep 13 19:36:17 fedora etherpad[304058]:     at Object.exports.start (/home/auniyal/custom_services/etherpad-lite/src/node/server.js:143:19)
Sep 13 19:36:17 fedora etherpad[304058]:     at runMicrotasks (<anonymous>)

```

Fortunately removing setting.json restored service.

Please update the doc for end-to-end enablement in README.

Thanks

**Comment by JohnMcLear** [comment]
Addressed in PR #182 — README now documents the supported install flow (admin UI or `pnpm run plugins install`) and explicitly warns against `npm i` from the Etherpad source tree. Closing.
